### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by cabreraalex** [ctfs/resources#11]
Rough road-map of what areas need to be worked on:
## General
- [ ] Polish contribution guides for tools, techs, and topics
- [ ] Add Recon, Hardware, etc. folders (topics) with README's
## Tools
- [ ] Explanation on operating systems and the benefits/downsides of OSX vs Windows vs Linux for CTFs
- [ ] Introduction to command line and terminal, does not have to be very in-depth and can link outside sources as there are plenty available.
### Cryptography
- [ ] Add a comprehensive _Getting Started_ section to README to help people begin learning simple crypto
- [ ] Add content and more variety of tactics, including finishing up incomplete topics and adding more
- [ ] Create and link `tools` articles from the cryptography articles, i.e. if you talk about a cracking tool in this section, write up a guide in the tools directory for it and link it
### Reversing
- [ ] There needs to be a solid intro for reverse engineering to really make this section useful
- [ ] Thorough introduction to IDA liked from tools directory
- [ ] Usage of hex editors
- [ ] Example tasks and solution walk-throughs for each technology and tool
### Steganography
- [ ] Topics on more advanced steganography tools and tactics
- [ ] Link to steg tools from tools directory
### Web
- [ ] Set up Heroku or similar web stacks and create simple web challenges for example
- [ ] Intro to types of web challenges, from SQL to XSS to HTTP

**Comment by mike-bailey** [comment]
Would you like assistance with this? Maybe I can fork, improve, and push upstream? Or is this intended to be a closed group of contributors.

**Comment by cabreraalex** [comment]
That would be awesome! My schoolwork and other commitments have prevented me from really working on this recently, so I would love if other people could contribute.  Please let me know if I can help out.

**Comment by AgentG010** [comment]
I was wondering if I and my friend could help too, we thought this was an amazing competition and we would love to contribute :)
